### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [mfiano/mfiano-utils#1]
Building with SBCL 2.2.11.160-65fe8bb77 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 65df8d45ce482a9922853e31e18c59a0d5f934d6

*mfiano-utils* fails to build with the following error:

```
Unhandled SB-EXT:SYMBOL-PACKAGE-LOCKED-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001710003}>: Lock on package SERAPEUM violated when defining PREPENDF as a macro while in package MFIANO-UTILS.

```

[Full log here](http://report.quicklisp.org/2022-12-24/failure-report/mfiano-utils.html)

**Comment by mfiano** [comment]
Thank you. It seems serapeum implemented `prependf` just a few days ago. I pushed a lazy fix for now. I haven't had a chance to inspect what serapeum's variant does, so I just removed the locally-defined version, since its use was nil.
